import daisyui from "daisyui";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      animation: {
        fadeIn: "fadeIn 1s ease-in-out",
        slideIn: "slideIn 0.7s ease-in-out",
        slideDown: "slideDown 0.5s cubic-bezier(0.4, 0, 0.2, 1)",
        pulseGlow: "pulseGlow 1.5s ease-in-out infinite",
        scaleIn: "scaleIn 0.8s ease-out",
        glassMorph: "glassMorph 0.6s cubic-bezier(0.4, 0, 0.2, 1) forwards",
        glassMorphPulse: "glassMorphPulse 0.8s cubic-bezier(0.34, 1.56, 0.64, 1)",
        dynamicScale: "dynamicScale 0.7s cubic-bezier(0.68, -0.55, 0.265, 1.55)",
        bounceInScale: "bounceInScale 0.8s cubic-bezier(0.68, -0.55, 0.265, 1.55)",
        gentleBounce: "gentleBounce 2s ease-in-out infinite",
        underlineGrow: "underlineGrow 0.5s cubic-bezier(0.4, 0, 0.2, 1)",
        subtleScale: "subtleScale 0.5s cubic-bezier(0.4, 0, 0.2, 1)",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: 0, transform: "translateY(10px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
        slideIn: {
          "0%": { opacity: 0, transform: "translateX(-10px)" },
          "100%": { opacity: 1, transform: "translateX(0)" },
        },
        slideDown: {
          "0%": { opacity: 0, transform: "translateY(-10px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
        pulseGlow: {
          "0%, 100%": { boxShadow: "0 0 10px rgba(255,255,255,0.3), 0 0 20px rgba(255,255,255,0.2)" },
          "50%": { boxShadow: "0 0 20px rgba(255,255,255,0.5), 0 0 30px rgba(255,255,255,0.3)" },
        },
        scaleIn: {
          "0%": { opacity: 0, transform: "scale(0.95)" },
          "100%": { opacity: 1, transform: "scale(1)" },
        },
        glassMorph: {
          "0%": { opacity: 0, transform: "scale(0.97) translateY(8px)", filter: "blur(1.5px)" },
          "100%": { opacity: 1, transform: "scale(1) translateY(0)", filter: "blur(0)" },
        },
        glassMorphPulse: {
          "0%": { opacity: 0, transform: "scale(0.98) translateY(10px)", filter: "blur(2px)", boxShadow: "0 0 15px rgba(255,255,255,0.2)" },
          "100%": { opacity: 1, transform: "scale(1) translateY(0)", filter: "blur(0)", boxShadow: "0 0 25px rgba(255,255,255,0.4)" },
        },
        dynamicScale: {
          "0%": { transform: "scale(0.95)", opacity: 0.8 },
          "50%": { transform: "scale(1.05)" },
          "100%": { transform: "scale(1)", opacity: 1 },
        },
        bounceInScale: {
          "0%": { transform: "scale(0.8)", opacity: 0 },
          "50%": { transform: "scale(1.1)" },
          "100%": { transform: "scale(1)", opacity: 1 },
        },
        spinSlow: {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        underlineGrow: {
          "0%": { width: "0%" },
          "100%": { width: "100%" },
        },
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
        roboto: ["Roboto", "sans-serif"],
        poppins: ["Poppins", "sans-serif"],
        montserrat: ["Montserrat", "sans-serif"],
        opensans: ["Open Sans", "sans-serif"],
        lato: ["Lato", "sans-serif"],
        nunito: ["Nunito", "sans-serif"],
        raleway: ["Raleway", "sans-serif"],
        orbitron: ["Orbitron", "sans-serif"],
        georgia: ["Georgia", "serif"],
        lora: ["Lora", "serif"],
        merriweather: ["Merriweather", "serif"],
        robotoMono: ["Roboto Mono", "monospace"],
        playfair: ["Playfair Display", "serif"],
        firaCode: ["Fira Code", "monospace"],
        quicksand: ["Quicksand", "sans-serif"],
        spaceMono: ["Space Mono", "monospace"],
        sanfrancisco: ["-apple-system", "BlinkMacSystemFont", "sans-serif"],
      },
    },
  },
  safelist: [
    "font-inter",
    "font-roboto",
    "font-poppins",
    "font-montserrat",
    "font-opensans",
    "font-lato",
    "font-nunito",
    "font-raleway",
    "font-orbitron",
    "font-georgia",
    "font-lora",
    "font-merriweather",
    "font-robotoMono",
    "font-playfair",
    "font-firaCode",
    "font-quicksand",
    "font-spaceMono",
    "font-sanfrancisco",
  ],
  plugins: [daisyui],
  daisyui: {
    themes: Object.keys(require("./src/constants/themes.js").THEME_COLORS).map(theme => ({
      [theme]: {
        primary: require("./src/constants/themes.js").THEME_COLORS[theme].primary,
        secondary: require("./src/constants/themes.js").THEME_COLORS[theme].secondary,
        tertiary: require("./src/constants/themes.js").THEME_COLORS[theme].tertiary,
        quaternary: require("./src/constants/themes.js").THEME_COLORS[theme].quaternary,
        accent: require("./src/constants/themes.js").THEME_COLORS[theme].tertiary,
        neutral: require("./src/constants/themes.js").THEME_COLORS[theme].quaternary,
        "base-100": require("./src/constants/themes.js").THEME_COLORS[theme]["base-100"],
        "base-200": require("./src/constants/themes.js").THEME_COLORS[theme]["base-200"],
        "base-300": require("./src/constants/themes.js").THEME_COLORS[theme]["base-300"],
        "base-content": require("./src/constants/themes.js").THEME_COLORS[theme]["base-content"],
        "primary-content": require("./src/constants/themes.js").THEME_COLORS[theme]["primary-content"],
        "secondary-content": require("./src/constants/themes.js").THEME_COLORS[theme]["secondary-content"],
        "tertiary-content": require("./src/constants/themes.js").THEME_COLORS[theme]["tertiary-content"],
        "quaternary-content": require("./src/constants/themes.js").THEME_COLORS[theme]["quaternary-content"],
      },
    })),
  },
};