export const THEMES = [
  "daylight",
  "midnight",
  "candyPop",
  "forestPine",
  "neonWave",
  "sandDune",
  "arcticBlue",
  "tangerine",
  "velvetRose",
  "cyberGrape",
  "sageMist",
  "emberGlow",
  "aquaDream",
  "sunsetPeach",
  "onyxGold",
  "mintChip",
  "stormCloud",
  "orchidBloom",
  "cobaltSky",
  "copperLeaf",
  "bubblegum",
  "deepSea",
  "citrusTwist",
  "lavenderFog",
  "rubyWine",
  "jadeGarden",
  "polarNight",
  "lemonMeringue",
  "graphite",
  "terraCotta",
];

export const THEME_COLORS = {
  daylight: {
    primary: "#f9fafb",
    secondary: "#f1f5f9",
    tertiary: "#e0e7ef",
    quaternary: "#2563eb",
    theme_color: "#2563eb",
    background_color: "#f9fafb",
    font: "Inter, sans-serif",
    "primary-content": "#22223b",
    "secondary-content": "#2563eb",
    "tertiary-content": "#22223b",
    "quaternary-content": "#fff",
    "base-100": "#f9fafb",
    "base-200": "#f1f5f9",
    "base-300": "#e0e7ef",
    "base-content": "#22223b",
  },
  midnight: {
    primary: "#18181b",
    secondary: "#23242a",
    tertiary: "#3f3f46",
    quaternary: "#6366f1",
    theme_color: "#6366f1",
    background_color: "#18181b",
    font: "SF Pro Display, sans-serif",
    "primary-content": "#f3f4f6",
    "secondary-content": "#fff",
    "tertiary-content": "#f3f4f6",
    "quaternary-content": "#fff",
    "base-100": "#18181b",
    "base-200": "#23242a",
    "base-300": "#3f3f46",
    "base-content": "#f3f4f6",
  },
  candyPop: {
    primary: "#ffb3c6",
    secondary: "#ff8fab",
    tertiary: "#fb6f92",
    quaternary: "#fff0f6",
    theme_color: "#fb6f92",
    background_color: "#fff0f6",
    font: "Poppins, sans-serif",
    "primary-content": "#ad1457",
    "secondary-content": "#fff",
    "tertiary-content": "#ad1457",
    "quaternary-content": "#fff",
    "base-100": "#fff0f6",
    "base-200": "#ffb3c6",
    "base-300": "#ff8fab",
    "base-content": "#ad1457",
  },
  forestPine: {
    primary: "#264653",
    secondary: "#2a9d8f",
    tertiary: "#e9c46a",
    quaternary: "#f4a261",
    theme_color: "#2a9d8f",
    background_color: "#e9c46a",
    font: "Lato, sans-serif",
    "primary-content": "#264653",
    "secondary-content": "#fff",
    "tertiary-content": "#264653",
    "quaternary-content": "#fff",
    "base-100": "#e9c46a",
    "base-200": "#2a9d8f",
    "base-300": "#264653",
    "base-content": "#264653",
  },
  neonWave: {
    primary: "#0ff0fc",
    secondary: "#ff00ea",
    tertiary: "#0a0a23",
    quaternary: "#fff200",
    theme_color: "#ff00ea",
    background_color: "#0a0a23",
    font: "Orbitron, sans-serif",
    "primary-content": "#fff200",
    "secondary-content": "#0ff0fc",
    "tertiary-content": "#ff00ea",
    "quaternary-content": "#0a0a23",
    "base-100": "#0a0a23",
    "base-200": "#0ff0fc",
    "base-300": "#ff00ea",
    "base-content": "#fff200",
  },
  sandDune: {
    primary: "#e4c590",
    secondary: "#c2b280",
    tertiary: "#a68a64",
    quaternary: "#4b2e1a",
    theme_color: "#c2b280",
    background_color: "#e4c590",
    font: "Georgia, serif",
    "primary-content": "#4b2e1a",
    "secondary-content": "#fff",
    "tertiary-content": "#4b2e1a",
    "quaternary-content": "#fff",
    "base-100": "#e4c590",
    "base-200": "#c2b280",
    "base-300": "#a68a64",
    "base-content": "#4b2e1a",
  },
  arcticBlue: {
    primary: "#e0f7fa",
    secondary: "#00bcd4",
    tertiary: "#4dd0e1",
    quaternary: "#01579b",
    theme_color: "#00bcd4",
    background_color: "#e0f7fa",
    font: "Montserrat, sans-serif",
    "primary-content": "#01579b",
    "secondary-content": "#fff",
    "tertiary-content": "#01579b",
    "quaternary-content": "#fff",
    "base-100": "#e0f7fa",
    "base-200": "#b2ebf2",
    "base-300": "#4dd0e1",
    "base-content": "#01579b",
  },
  tangerine: {
    primary: "#ffb347",
    secondary: "#ff7f50",
    tertiary: "#b3541e",
    quaternary: "#fffbe7",
    theme_color: "#ffb347",
    background_color: "#fffbe7",
    font: "Georgia, serif",
    "primary-content": "#b3541e",
    "secondary-content": "#fff",
    "tertiary-content": "#b3541e",
    "quaternary-content": "#fff",
    "base-100": "#fffbe7",
    "base-200": "#ffe5b4",
    "base-300": "#ffb347",
    "base-content": "#b3541e",
  },
  velvetRose: {
    primary: "#b76e79",
    secondary: "#f7cac9",
    tertiary: "#fff0f5",
    quaternary: "#6b2737",
    theme_color: "#b76e79",
    background_color: "#fff0f5",
    font: "Lora, serif",
    "primary-content": "#6b2737",
    "secondary-content": "#fff",
    "tertiary-content": "#b76e79",
    "quaternary-content": "#fff",
    "base-100": "#fff0f5",
    "base-200": "#f7cac9",
    "base-300": "#b76e79",
    "base-content": "#6b2737",
  },
  cyberGrape: {
    primary: "#5d3fd3",
    secondary: "#a084ca",
    tertiary: "#f7f7f7",
    quaternary: "#1b1b2f",
    theme_color: "#5d3fd3",
    background_color: "#1b1b2f",
    font: "Roboto Mono, monospace",
    "primary-content": "#f7f7f7",
    "secondary-content": "#fff",
    "tertiary-content": "#5d3fd3",
    "quaternary-content": "#fff",
    "base-100": "#1b1b2f",
    "base-200": "#a084ca",
    "base-300": "#5d3fd3",
    "base-content": "#f7f7f7",
  },
  sageMist: {
    primary: "#e9f5db",
    secondary: "#52b788",
    tertiary: "#b7e4c7",
    quaternary: "#1b4332",
    theme_color: "#52b788",
    background_color: "#e9f5db",
    font: "Nunito, sans-serif",
    "primary-content": "#1b4332",
    "secondary-content": "#fff",
    "tertiary-content": "#1b4332",
    "quaternary-content": "#fff",
    "base-100": "#e9f5db",
    "base-200": "#b7e4c7",
    "base-300": "#52b788",
    "base-content": "#1b4332",
  },
  emberGlow: {
    primary: "#ff7043",
    secondary: "#ffb300",
    tertiary: "#fffbe7",
    quaternary: "#d84315",
    theme_color: "#ffb300",
    background_color: "#fffbe7",
    font: "Quicksand, sans-serif",
    "primary-content": "#d84315",
    "secondary-content": "#fff",
    "tertiary-content": "#fff",
    "quaternary-content": "#fff",
    "base-100": "#fffbe7",
    "base-200": "#ffe082",
    "base-300": "#ffb300",
    "base-content": "#d84315",
  },
  aquaDream: {
    primary: "#b9fbc0",
    secondary: "#70d6ff",
    tertiary: "#38bdf8",
    quaternary: "#22223b",
    theme_color: "#38bdf8",
    background_color: "#e0f7fa",
    font: "Nunito, sans-serif",
    "primary-content": "#065f46",
    "secondary-content": "#065f46",
    "tertiary-content": "#065f46",
    "quaternary-content": "#065f46",
    "base-100": "#b9fbc0",
    "base-200": "#70d6ff",
    "base-300": "#38bdf8",
    "base-content": "#065f46",
  },
  sunsetPeach: {
    primary: "#ffb3ab",
    secondary: "#ffd6a5",
    tertiary: "#fdffb6",
    quaternary: "#cdb4db",
    theme_color: "#ffb3ab",
    background_color: "#fdffb6",
    font: "Raleway, sans-serif",
    "primary-content": "#cdb4db",
    "secondary-content": "#fff",
    "tertiary-content": "#ffb3ab",
    "quaternary-content": "#fff",
    "base-100": "#fdffb6",
    "base-200": "#ffd6a5",
    "base-300": "#ffb3ab",
    "base-content": "#cdb4db",
  },
  onyxGold: {
    primary: "#23272a",
    secondary: "#ffd700",
    tertiary: "#bfa980",
    quaternary: "#fffbe7",
    theme_color: "#ffd700",
    background_color: "#23272a",
    font: "Roboto Mono, monospace",
    "primary-content": "#ffd700",
    "secondary-content": "#23272a",
    "tertiary-content": "#fffbe7",
    "quaternary-content": "#fff",
    "base-100": "#23272a",
    "base-200": "#ffd700",
    "base-300": "#bfa980",
    "base-content": "#ffd700",
  },
  mintChip: {
    primary: "#e0fbfc",
    secondary: "#3ddad7",
    tertiary: "#a7ffeb",
    quaternary: "#293241",
    theme_color: "#3ddad7",
    background_color: "#e0fbfc",
    font: "Nunito, sans-serif",
    "primary-content": "#293241",
    "secondary-content": "#fff",
    "tertiary-content": "#293241",
    "quaternary-content": "#fff",
    "base-100": "#e0fbfc",
    "base-200": "#a7ffeb",
    "base-300": "#3ddad7",
    "base-content": "#293241",
  },
  stormCloud: {
    primary: "#64748b",
    secondary: "#334155",
    tertiary: "#0f172a",
    quaternary: "#f1f5f9",
    theme_color: "#64748b",
    background_color: "#f1f5f9",
    font: "Roboto Mono, monospace",
    "primary-content": "#0f172a",
    "secondary-content": "#fff",
    "tertiary-content": "#0f172a",
    "quaternary-content": "#fff",
    "base-100": "#f1f5f9",
    "base-200": "#64748b",
    "base-300": "#334155",
    "base-content": "#0f172a",
  },
  orchidBloom: {
    primary: "#ede9fe",
    secondary: "#a78bfa",
    tertiary: "#c4b5fd",
    quaternary: "#7c3aed",
    theme_color: "#a78bfa",
    background_color: "#ede9fe",
    font: "Merriweather, serif",
    "primary-content": "#7c3aed",
    "secondary-content": "#fff",
    "tertiary-content": "#7c3aed",
    "quaternary-content": "#fff",
    "base-100": "#ede9fe",
    "base-200": "#c4b5fd",
    "base-300": "#a78bfa",
    "base-content": "#7c3aed",
  },
  cobaltSky: {
    primary: "#e3f2fd",
    secondary: "#90caf9",
    tertiary: "#42a5f5",
    quaternary: "#0d47a1",
    theme_color: "#1976d2",
    background_color: "#e3f2fd",
    font: "Raleway, sans-serif",
    "primary-content": "#0d47a1",
    "secondary-content": "#fff",
    "tertiary-content": "#0d47a1",
    "quaternary-content": "#fff",
    "base-100": "#e3f2fd",
    "base-200": "#bbdefb",
    "base-300": "#90caf9",
    "base-content": "#0d47a1",
  },
  copperLeaf: {
    primary: "#b87333",
    secondary: "#c0a98e",
    tertiary: "#e6ccb2",
    quaternary: "#4b2e1a",
    theme_color: "#b87333",
    background_color: "#e6ccb2",
    font: "Georgia, serif",
    "primary-content": "#4b2e1a",
    "secondary-content": "#fff",
    "tertiary-content": "#b87333",
    "quaternary-content": "#fff",
    "base-100": "#e6ccb2",
    "base-200": "#c0a98e",
    "base-300": "#b87333",
    "base-content": "#4b2e1a",
  },
  bubblegum: {
    primary: "#ffb7b2",
    secondary: "#ffdac1",
    tertiary: "#b5ead7",
    quaternary: "#c7ceea",
    theme_color: "#ffb7b2",
    background_color: "#ffdac1",
    font: "Poppins, sans-serif",
    "primary-content": "#c7ceea",
    "secondary-content": "#fff",
    "tertiary-content": "#ffb7b2",
    "quaternary-content": "#fff",
    "base-100": "#ffdac1",
    "base-200": "#b5ead7",
    "base-300": "#ffb7b2",
    "base-content": "#c7ceea",
  },
  deepSea: {
    primary: "#003049",
    secondary: "#669bbc",
    tertiary: "#fdf0d5",
    quaternary: "#780000",
    theme_color: "#003049",
    background_color: "#fdf0d5",
    font: "Roboto, sans-serif",
    "primary-content": "#003049",
    "secondary-content": "#fff",
    "tertiary-content": "#003049",
    "quaternary-content": "#fff",
    "base-100": "#fdf0d5",
    "base-200": "#669bbc",
    "base-300": "#003049",
    "base-content": "#003049",
  },
  citrusTwist: {
    primary: "#fffde7",
    secondary: "#fff176",
    tertiary: "#ffd600",
    quaternary: "#ffab00",
    theme_color: "#ffd600",
    background_color: "#fffde7",
    font: "Quicksand, sans-serif",
    "primary-content": "#b45309",
    "secondary-content": "#fff",
    "tertiary-content": "#b45309",
    "quaternary-content": "#fff",
    "base-100": "#fffde7",
    "base-200": "#fff176",
    "base-300": "#ffd600",
    "base-content": "#b45309",
  },
  lavenderFog: {
    primary: "#f3e8ff",
    secondary: "#a78bfa",
    tertiary: "#e0bbff",
    quaternary: "#7c3aed",
    theme_color: "#a78bfa",
    background_color: "#f3e8ff",
    font: "Merriweather, serif",
    "primary-content": "#7c3aed",
    "secondary-content": "#fff",
    "tertiary-content": "#7c3aed",
    "quaternary-content": "#fff",
    "base-100": "#f3e8ff",
    "base-200": "#ede7f6",
    "base-300": "#e0bbff",
    "base-content": "#7c3aed",
  },
  rubyWine: {
    primary: "#7b2c2c",
    secondary: "#c44536",
    tertiary: "#e0a899",
    quaternary: "#fbeee6",
    theme_color: "#c44536",
    background_color: "#fbeee6",
    font: "Playfair Display, serif",
    "primary-content": "#7b2c2c",
    "secondary-content": "#fff",
    "tertiary-content": "#c44536",
    "quaternary-content": "#fff",
    "base-100": "#fbeee6",
    "base-200": "#e0a899",
    "base-300": "#c44536",
    "base-content": "#7b2c2c",
  },
  jadeGarden: {
    primary: "#a7ffeb",
    secondary: "#43aa8b",
    tertiary: "#254441",
    quaternary: "#e8f6ef",
    theme_color: "#43aa8b",
    background_color: "#e8f6ef",
    font: "Lato, sans-serif",
    "primary-content": "#254441",
    "secondary-content": "#fff",
    "tertiary-content": "#254441",
    "quaternary-content": "#fff",
    "base-100": "#e8f6ef",
    "base-200": "#a7ffeb",
    "base-300": "#43aa8b",
    "base-content": "#254441",
  },
  polarNight: {
    primary: "#232946",
    secondary: "#121629",
    tertiary: "#b8c1ec",
    quaternary: "#eebbc3",
    theme_color: "#232946",
    background_color: "#121629",
    font: "Fira Code, monospace",
    "primary-content": "#eebbc3",
    "secondary-content": "#fff",
    "tertiary-content": "#232946",
    "quaternary-content": "#fff",
    "base-100": "#232946",
    "base-200": "#121629",
    "base-300": "#b8c1ec",
    "base-content": "#eebbc3",
  },
  lemonMeringue: {
    primary: "#fffde7",
    secondary: "#fff176",
    tertiary: "#ffd600",
    quaternary: "#ffab00",
    theme_color: "#ffd600",
    background_color: "#fffde7",
    font: "Quicksand, sans-serif",
    "primary-content": "#b45309",
    "secondary-content": "#fff",
    "tertiary-content": "#b45309",
    "quaternary-content": "#fff",
    "base-100": "#fffde7",
    "base-200": "#fff176",
    "base-300": "#ffd600",
    "base-content": "#b45309",
  },
  graphite: {
    primary: "#23272a",
    secondary: "#2c2f33",
    tertiary: "#99aab5",
    quaternary: "#7289da",
    theme_color: "#7289da",
    background_color: "#23272a",
    font: "Roboto Mono, monospace",
    "primary-content": "#fff",
    "secondary-content": "#fff",
    "tertiary-content": "#23272a",
    "quaternary-content": "#fff",
    "base-100": "#23272a",
    "base-200": "#2c2f33",
    "base-300": "#99aab5",
    "base-content": "#fff",
  },
  terraCotta: {
    primary: "#e2725b",
    secondary: "#f7c59f",
    tertiary: "#b5838d",
    quaternary: "#6d6875",
    theme_color: "#e2725b",
    background_color: "#f7c59f",
    font: "Lora, serif",
    "primary-content": "#6d6875",
    "secondary-content": "#fff",
    "tertiary-content": "#e2725b",
    "quaternary-content": "#fff",
    "base-100": "#f7c59f",
    "base-200": "#e2725b",
    "base-300": "#b5838d",
    "base-content": "#6d6875",
  },
};